### ISSUE TITLE
已录入的游戏，在游戏库-编辑游戏时，只能编辑图标

### ISSUE THREAD

**Issue by zyhstellar** [Summer-Neko/NekoGame#1]
已录入的游戏，在游戏库-编辑游戏时，只能编辑图标。游戏海报（竖版）、游戏海报（横版）无法编辑

**Comment by Summer-Neko** [comment]
问题确实存在，我尽早处理！

**Comment by Summer-Neko** [comment]
已经修复了，看看会不会还有其他问题。

**Comment by zyhstellar** [comment]
目前用着正常了。作者大大好快的修！你的这个工具对我来说简直是雪中送炭。很多游戏不在steam，而我有统计时间的需求，好多年都是拿个表计时然后记在本子上....

**Comment by Summer-Neko** [comment]
很高兴帮到你！ヾ(≧▽≦*)o
