### ISSUE TITLE
鸣潮祈愿分析无用

### ISSUE THREAD

**Issue by zyhstellar** [Summer-Neko/NekoGame#6]
我打开了唤取记录，翻了几个页面，点鸣潮祈愿分析弹窗：【刷新失败:读取日志文件失败】

**Comment by Summer-Neko** [comment]
郁闷了，你的鸣潮安装在哪？有可能是权限不够的原因，你试试管理员启动看看？或者退出鸣潮，有可能是因为游戏锁定了日志文件。我电脑上没有这个情况(ノへ￣、)

**Comment by Summer-Neko** [comment]
推送了尝试修复的版本，你试试看有没有效果？

**Comment by zyhstellar** [comment]
我装了最新版本，而且右键管理员运行，报错：【刷新失败:无法复制日志文件，可能被锁定或不存在】，尝试了游戏运行中重新启动nekogame，或者先启动了nekogame再启动鸣潮都不行...

游戏安装目录：I:\Wuthering Waves Game，游戏通过在桌面的快捷方式启动Wuthering Waves.exe
nekogame安装目录：C:\Users\ZYH\AppData\Local\Programs\NekoGame

**Comment by zyhstellar** [comment]
![Uploading 微信截图_20241120000040.png…]()

**Comment by zyhstellar** [comment]
![微信截图_20241120000040](https://github.com/user-attachments/assets/a7d468ab-4a12-4cd5-bd8d-327793858b9b)

**Comment by Summer-Neko** [comment]
很奇怪的问题(っ °Д °;)っ，你确认一下I:\Wuthering Waves\Wuthering Waves Game\Client\Saved\Logs路径下有没有Client.log。我试过其他电脑，包括其他人的反馈，获取链接都是很顺畅的。
如果存在Client.log，如果你的I盘下就是Wuthering Waves Game文件夹，那确实也可能会有这样的问题。请确认一下你安装完鸣潮后有没有手动移动过游戏文件夹。

**Comment by Summer-Neko** [comment]
你的难道是wegame启动的吗？可能情况有些不一样

**Comment by zyhstellar** [comment]
问题解决了，我就是在通过官方启动器下载然后手动剪切换了路径。

**Comment by Summer-Neko** [comment]
很高兴听到问题解决了q(≧▽≦q)
