### ISSUE TITLE
技术选型建议

### ISSUE THREAD

**Issue by illusionGD** [Summer-Neko/NekoGame#7]
建议用比较热门的前端技术：
1. 框架：vue/react，可以找找相关的electron仓库
2. css扩展语言：sass/less
3. 语言：ts
4. 包管理：pnpm可以解决幽灵依赖和重复安装包的问题
5. 规范：eslint语法检测，prettier自动格式代码
6. 打包工具：vite/webpack
7. githook：husky

**Comment by Summer-Neko** [comment]
谢谢建议！我目前还在学习。未来会尝试使用更多的技术，并努力提升我的开发水平

**Comment by illusionGD** [comment]
> 谢谢建议！我目前还在学习。未来会尝试使用更多的技术，并努力提升我的开发水平

请问有群吗，我也想参与建设，最近也想搞搞electron的

**Comment by Summer-Neko** [comment]
没有群哦，目前也还没有扩展开发人员的打算＞﹏＜
