### ISSUE TITLE
绝区零常驻角色有误

### ISSUE THREAD

**Issue by Qihang-Li** [Summer-Neko/NekoGame#8]
见附图，11号被认为是不歪的角色

![image](https://github.com/user-attachments/assets/b44089ef-0411-43ad-9cd2-7bfe3748941b)

**Comment by Summer-Neko** [comment]
已经调整了，调整后的版本在度盘的测试版里，可以下载看看问题有没有解决。测试版可以正常更新到正式版。

**Comment by Summer-Neko** [comment]
> 好的谢谢。我这边看2.3.5版本已经修复了

嗯，感谢反馈啦
