### ISSUE TITLE
无法修改游戏信息

### ISSUE THREAD

**Issue by alicekagiyama** [Summer-Neko/NekoGame#9]
添加游戏后，游戏栏目没法对已添加的游戏进行修改，‘’游戏库‘’一栏的菜单仅有‘录入游戏’一个选项；
基于上述原因，目前没找到可以填入信息的方式，包括UID等核心信息，因此完全无法读取任何抽卡信息

**Comment by Summer-Neko** [comment]
谢谢反馈啦，游戏信息更改需要在对应游戏右侧出勤表上方的省略号中调整，包括删除也是。

>完全无法读取任何抽卡信息

另外，请问是哪个游戏无法获取抽卡信息？目前除了绝区零和鸣潮WeGame启动的以外，都不需要额外导入游戏信息就可以自动获取抽卡记录了。

**Comment by alicekagiyama** [comment]
> 谢谢反馈啦，游戏信息更改需要在对应游戏右侧出勤表上方的省略号中调整，包括删除也是。
> 
> > 完全无法读取任何抽卡信息
> 
> 另外，请问是哪个游戏无法获取抽卡信息？目前除了绝区零和鸣潮WeGame启动的以外，都不需要额外导入游戏信息就可以自动获取抽卡记录了。

测试的是绝区零，今天看了你的回复后又试了下，不会出现之前说的缺少UID啥的报错，正常读取了。
个人猜测是之前我关掉了全局VPN，跟官方的网络连接有问题（电脑之前有段时间不挂VPN甚至无法连上游戏网络），今天在全局VPN的状态下是正常读取了。
